.PHONY:analyse

analyse:
	sonar-scanner   -Dsonar.projectKey=first   -Dsonar.sources=.   -Dsonar.host.url=http://localhost:9000   -Dsonar.token=sqp_333a85371d6551cd322ced32ed96c8b5fd55c416


print:
	echo "Hello World"