name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if requirements are in a different location

      # Step 4: Set up the database (SQLite for testing)
      - name: Make migrations
        working-directory: ToDoListProj
        run: python manage.py makemigrations

      - name: Run migrations
        working-directory: ToDoListProj
        run: python manage.py migrate

      # Step 5: Run tests
      - name: Run tests
        working-directory: ToDoListProj
        run: python manage.py test
