
name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version your project requires

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if requirements are in a different location

      # Step 4: Set up the database (SQLite for testing)
      - name: Make migrations
        working-directory: ToDoListProj
        run: python manage.py makemigrations

      - name: Run migrations
        working-directory: ToDoListProj
        run: python manage.py migrate

      # Step 5: Run tests
      - name: Run tests
        working-directory: ToDoListProj
        run: python manage.py test

      # Step 6: Install SonarScanner
      - name: Install SonarScanner
        run: |
          # Download SonarScanner
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      # Step 7: Run SonarQube analysis
      - name: Run SonarQube analysis
        run: |
          # Set SonarQube authentication token and URL
          export SONAR_HOST_URL="http://sonarqube.homeserver-ericp.fr"
          export SONAR_LOGIN="ilias.ouandouri"
          export SONAR_PASSWORD="Ynov:::2024:Web"

          # Run sonar-scanner with the appropriate properties
          sonar-scanner \
            -Dsonar.projectKey=first \
            -Dsonar.sources=ToDoListProj/app \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_LOGIN \
            -Dsonar.password=$SONAR_PASSWORD \
            -Dsonar.python.coverage.reportPaths=coverage.lcov




# name: Build and Test

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Check out the code from your repository
#       - name: Check out code
#         uses: actions/checkout@v2

#       # Step 2: Set up Python environment
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'  # Specify the Python version your project requires

#       # Step 3: Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt  # Adjust if requirements are in a different location

#       # Step 4: Set up the database (SQLite for testing)
#       - name: Make migrations
#         working-directory: ToDoListProj
#         run: python manage.py makemigrations

#       - name: Run migrations
#         working-directory: ToDoListProj
#         run: python manage.py migrate

#       # Step 5: Run tests
#       - name: Run tests
#         working-directory: ToDoListProj
#         run: python manage.py test
